name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo add-apt-repository ppa:vriviere/ppa && sudo apt-get update
        sudo apt-get install cross-mint-essential dos2unix lftp hatari aranym mtools
    - name: Display package versions
      run: |
        git --version
        make --version
        ld --version
        gcc --version
        awk -W version
        m68k-atari-mint-ld --version
        m68k-atari-mint-gcc --version
        tar --version
        unix2dos --version
        lftp --version
    - name: Build binaries
      run: |
        export VERSION=$(date -u +%Y%m%d-%H%M%S)-$(git rev-parse --short ${GITHUB_SHA})
        echo VERSION=$VERSION
        make clean
        make release VERSION=$VERSION
    - name: Save binaries as build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: emutos-${{env.VERSION}}
        path: release-archives/
