name: EmuTOS build, test and deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04

    # Prevent forks from running this job.
    # Note that this is merely for convenience, to avoid forks from being
    # bothered by failing GitHub Actions jobs. Forks cannot accidentally
    # or deliberately deploy to EmuTOS SourceForge page without access
    # to the SSH key.
    if: ${{startsWith( github.repository, 'czietz/' ) }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install SSH keys
      env:
        SSH_ID: ${{ secrets.SSH_ID }}
      run: .scripts/install_ssh_id.sh
    - name: Install packages
      run: |
        sudo add-apt-repository ppa:vriviere/ppa && sudo apt-get update
        sudo apt-get install cross-mint-essential dos2unix lftp hatari aranym mtools
    - name: Display package versions
      run: |
        git --version
        make --version
        ld --version
        gcc --version
        awk -W version
        m68k-atari-mint-ld --version
        m68k-atari-mint-gcc --version
        tar --version
        unix2dos --version
        lftp --version
    - name: Build binaries
      run: |
        export VERSION=$(date -u +%Y%m%d-%H%M%S)-$(git rev-parse --short ${GITHUB_SHA})
        echo VERSION=$VERSION >> $GITHUB_ENV
        echo VERSION=$VERSION
        make clean
        make release VERSION=$VERSION
    - name: Add README.md
      env:
        COMPARE_URL: ${{ github.event.compare }}
        PREVIOUS_COMMIT: ${{ github.event.before }}
        CURRENT_COMMIT: ${{ github.event.after }}
      run: .scripts/generate-readme.sh >release-archives/README.md
    - name: Display resulting tree
      run: ls -l release-archives
    - name: Test the build
      run: |
        unzip release-archives/emutos-512k-*.zip
        make test EMUTOS=$(ls $PWD/emutos-512k-*/etos512k.img)
    - name: Deploy to SourceForge
      run: |
        cp release-archives/README.md release-archives/commits.txt
        .scripts/deploy.sh
